# Generated by Django 5.0.3 on 2024-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
