# Generated by Django 5.0.3 on 2024-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
